# Generated by Django 4.2 on 2023-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, db_column='APPOINTMENT_DATETIME', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(db_column='MIDDLE_NAME', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(db_column='MIDDLE_NAME', max_length=300, null=True),
        ),
    ]
