# Generated by Django 4.2 on 2023-04-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_clinic_clinic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctor',
            field=models.ManyToManyField(blank=True, db_column='CLINIC_ID', related_name='clinic_id', through='appointments.Appointments', to='appointments.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorClinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='MODIFIED_DATE')),
                ('Clinic', models.ForeignKey(db_column='CLINIC', on_delete=django.db.models.deletion.CASCADE, to='appointments.clinic')),
                ('doctor', models.ForeignKey(db_column='Doctor', on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor')),
            ],
            options={
                'db_table': 'DOCTOR_CLINICS',
            },
        ),
    ]
