# Generated by Django 4.2 on 2023-04-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_doctor_middle_name_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='PATIENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient_id', to='appointments.patient'),
        ),
    ]
