# Generated by Django 4.2 on 2023-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_name',
            field=models.CharField(db_column='CLINIC_NAME', default='', max_length=300),
            preserve_default=False,
        ),
    ]
