# Generated by Django 4.2 on 2023-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_clinic_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.ManyToManyField(blank=True, db_column='DOCTOR_ID', related_name='mm_doctor_id', through='appointments.DoctorClinics', to='appointments.doctor'),
        ),
    ]
