# Generated by Django 4.2 on 2023-04-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointments_archived_clinic_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctor',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctor_clinic',
            field=models.ManyToManyField(blank=True, db_column='DOCTOR_ID', related_name='mm_doctor_id', to='appointments.doctor'),
        ),
    ]
