# Generated by Django 4.2 on 2023-04-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_clinic_doctor_clinic_doctor_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctor_clinic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(blank=True, db_column='DOCTOR_ID', related_name='mm_doctor_id', through='appointments.DoctorClinics', to='appointments.doctor'),
        ),
    ]
