# Generated by Django 4.2 on 2023-04-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_doctorclinics_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, db_column='CLINIC_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinic_id', to='appointments.clinic'),
        ),
        migrations.DeleteModel(
            name='DoctorClinics',
        ),
    ]
